
import json

features = []

def add_feature(category, description, steps, priority="medium"):
    features.append({
        "category": category,
        "description": description,
        "steps": steps,
        "passes": False,
        "priority": priority
    })

# Project Setup 1-10
add_feature("functional", "Initialize React project with Vite", ["Run npm create vite", "Select React", "Select TypeScript"], "high")
add_feature("functional", "Install Tailwind CSS", ["Run npm install -D tailwindcss postcss autoprefixer", "npx tailwindcss init -p"], "high")
add_feature("functional", "Configure Tailwind CSS", ["Update tailwind.config.js content", "Add directives to index.css"], "high")
add_feature("functional", "Install React Router", ["npm install react-router-dom"], "high")
add_feature("functional", "Install Framer Motion", ["npm install framer-motion"], "high")
add_feature("functional", "Setup Project Structure (components, pages, utils)", ["Create src/components", "Create src/pages", "Create src/utils", "Create src/assets"], "high")
add_feature("functional", "Setup Git repository", ["git init", "Create .gitignore"], "high")
add_feature("functional", "Create 404 Not Found Page", ["Create NotFound.tsx", "Add route * to NotFound"], "medium")
add_feature("functional", "Configure Path Aliases", ["Update vite.config.ts", "Update tsconfig.json"], "medium")
add_feature("functional", "Setup Linting and Formatting", ["Configure ESLint", "Configure Prettier"], "medium")

# Global UI 11-40
add_feature("style", "Create Global Layout Component", ["Create Layout.tsx", "Include Sidebar and Main Content area", "Verify spacing"], "high")
add_feature("style", "Design Navigation Sidebar", ["Create Sidebar component", "Add links to all modules", "Style active state"], "high")
add_feature("style", "Implement Responsive Sidebar", ["Add hamburger menu for mobile", " Verify collapse/expand on small screens"], "medium")
add_feature("style", "Define Color Palette in Tailwind", ["Add primary, secondary, accent colors", "Add semantic colors (success, error, warning)"], "high")
add_feature("style", "Set Global Typography", ["Import Google Fonts (Inter/Noto Sans SC)", "Apply to body"], "medium")
add_feature("style", "Create Button Component", ["Create Button.tsx", "Implement variants (primary, secondary, outline)", "Implement sizes"], "high")
add_feature("style", "Create Input Component", ["Create Input.tsx", "Style focus states", "Add error state styling"], "medium")
add_feature("style", "Create Card Component", ["Create Card.tsx", "Add shadow and border-radius", "Add hover effects"], "medium")
add_feature("style", "Create Modal Component", ["Create Modal.tsx", "Implement overlay and close button", "Add animation"], "medium")
add_feature("style", "Create Tooltip Component", ["Create Tooltip.tsx", "Show on hover", "Position correctly"], "medium")
add_feature("style", "Create Toggle/Switch Component", ["Create Toggle.tsx", "Animate ON/OFF state", "Support labels"], "medium")
add_feature("style", "Create Slider Component", ["Create Slider.tsx", "Style track and thumb", "Support min/max/step"], "medium")
add_feature("functional", "Implement Dark Mode Support", ["Add dark mode class toggle", "Define dark mode colors"], "low")
add_feature("functional", "Create Page PageHeader Component", ["Create PageHeader.tsx", "Display title and description"], "medium")
add_feature("functional", "Create Breadcrumbs Component", ["Create Breadcrumbs.tsx", "Auto-generate based on route"], "low")
add_feature("functional", "Create Footer Component", ["Create Footer.tsx", "Add copyright and links"], "low")
add_feature("style", "Global Animation Config", ["Define standard transitions", "Create animation utility constants"], "medium")
add_feature("style", "Scrollbar Styling", ["Customize scrollbar width and color", "Ensure cross-browser support"], "low")
add_feature("style", "Loading Spinner Component", ["Create Spinner.tsx", "Animate rotation"], "medium")
add_feature("style", "Error Boundary Component", ["Create ErrorBoundary.tsx", "Display friendly error message"], "medium")
add_feature("style", "Toast Notification System", ["Create ToastContext", "Implement Toast component", "Animate entry/exit"], "medium")
add_feature("style", "Glassmorphism Utility", ["Create glass effect CSS class", "Apply to overlay elements"], "medium")
add_feature("style", "Gradient Backgrounds", ["Define mesh gradient backgrounds", "Apply to specific pages"], "medium")
add_feature("functional", "Language Context (Chinese Default)", ["Verify generic texts are in Chinese", "Setup i18n structure if needed (hardcoded fine)"], "high")
add_feature("functional", "Accessibility Setup (Aria)", ["Ensure landmarks are used", "Check contrast ratios"], "medium")
add_feature("functional", "SEO Meta Tags Setup", ["Add Helmet or standard meta tags", "Set default title"], "medium")
add_feature("functional", "Favicon and Manifest", ["Add favicon.ico", "Create manifest.json"], "low")
add_feature("functional", "Mobile Viewport Meta", ["Ensure correct viewport settings", "Disable auto-zoom on input"], "medium")
add_feature("style", "Selection Color Customization", ["Customize ::selection CSS", "Match brand color"], "low")
add_feature("style", "Focus Ring Customization", ["Customize :focus-visible", "Match brand styles"], "low")

# TrianglePerimeter Module 41-55
add_feature("functional", "TrianglePerimeter Route Setup", ["Create page component", "Add route /triangle-perimeter"], "high")
add_feature("functional", "Triangle State Management", ["Store side lengths a, b, c", "Calculate validity condition"], "high")
add_feature("functional", "Triangle Rendering (Canvas/SVG)", ["Draw triangle based on lengths", "Handle invalid triangles visually"], "high")
add_feature("functional", "Input Controls for Sides", ["Add 3 sliders for a, b, c", "Limit ranges"], "high")
add_feature("functional", "Inequality Visualization", ["Display a + b > c text", "Highlight failing inequality"], "high")
add_feature("style", "Triangle Animation on Change", ["Animate vertices when sides change", "Smooth transition"], "medium")
add_feature("functional", "Broken Triangle Visual", ["Show sides collapsing if invalid", "Gap or overlap visualization"], "medium")
add_feature("style", "Triangle Color Coding", ["Color sides differently", "Legend for sides"], "low")
add_feature("functional", "Triangle Area Calc (Heron)", ["Calculate area (optional extra)", "Display value"], "low")
add_feature("functional", "Reset Triangle Button", ["Reset to default valid state", "Clear animations"], "low")
add_feature("style", "Triangle Instructions Panel", ["Add specific instructions", "Explain the theorem"], "medium")
add_feature("functional", "Triangle Quick Presets", ["Equilateral button", "Isosceles button", "Scalene button"], "medium")
add_feature("functional", "Triangle Invalid Alert", ["Show toast/alert when triangle breaks", "Explain why"], "medium")
add_feature("style", "Triangle Responsive Layout", ["Stack controls and canvas on mobile", "Side-by-side on desktop"], "medium")
add_feature("functional", "Triangle Unit Tests", ["Test valid inputs", "Test invalid inputs"], "low")

# CircleArea Module 56-80
add_feature("functional", "CircleArea Route Setup", ["Create page component", "Add route /circle-area"], "high")
add_feature("functional", "Circle Initial Render", ["Draw circle SVG", "Show radius and circumference props"], "high")
add_feature("functional", "Sector Slicing Logic", ["Calculate sector paths for N segments", "Support N=8, 16, 32, 64"], "high")
add_feature("style", "Segment Color Alternating", ["Color adjacent sectors differently", "Visual distinction"], "medium")
add_feature("functional", "Unfolding Animation Steps", ["Step 1: Separate sectors", "Step 2: Re-arrange top/bottom"], "high")
add_feature("functional", "Rectangular Formation", ["Align sectors to form 'rectangle'", "Handle 'teeth' interlocking"], "high")
add_feature("functional", "Fix Gap Bug (High Priority)", ["Ensure sectors fit perfectly", "Adjust coordinates for exact match"], "high")
add_feature("functional", "Slice Count Control", ["Dropdown/Slider for 8/16/32/64 slices", "Update visual immediately"], "high")
add_feature("functional", "Limit Demonstration", ["Show how 64 looks like a rectangle", "Comparing curves to straight lines"], "high")
add_feature("functional", "Area Formula Derivation UI", ["Show Pi*r * r text", "Map rectangle W/H to Pi*r and r"], "high")
add_feature("style", "Smooth Transition Animation", ["Animate from Circle to Rectangle", "Reversible animation"], "medium")
add_feature("functional", "Step-by-Step Guide Mode", ["Next/Prev buttons", "Text description per step"], "medium")
add_feature("functional", "Instructions Text", ["Explain cut-and-paste method", "Highlight target knowledge"], "medium")
add_feature("style", "Zoom Controls", ["Zoom in to see the 'curve' vs 'straight'", "Pan support"], "low")
add_feature("functional", "Reset Circle Animation", ["Return to initial circle state", "Stop all animations"], "low")
add_feature("style", "Sector Border Styling", ["Thin borders for clarity", "Remove borders for high N?"], "low")
add_feature("functional", "Show/Hide Radius", ["Toggle radius indicator", "Show r annotation"], "low")
add_feature("functional", "Show/Hide Circumference", ["Toggle C indicator", "Show C/2 annotation"], "low")
add_feature("functional", "Interactive Radius Slider", ["Change circle size", "Scale everything"], "medium")
add_feature("style", "Transition Speed Control", ["Slow/Medium/Fast", "Adjust duration"], "low")
add_feature("style", "Enhanced Tooltips", ["Hover over parts to see 'Radius'", "'Circumference/2'"], "low")
add_feature("functional", "Performance Optimization", ["Ensure 64 slices animate smoothly", "Use CSS transforms or Canvas"], "high")
add_feature("functional", "Mobile Touch Support", ["Swipe to advance steps?", "Ensure buttons tapping"], "medium")
add_feature("style", "Background Grid", ["Optional grid to judge straightness", "Toggle grid"], "low")
add_feature("functional", "Comparison Overlay", ["Overlay a true rectangle", "Show difference"], "medium")

# TreePlanting Module 81-110
add_feature("functional", "TreePlanting Route Setup", ["Create page component", "Add route /tree-planting"], "high")
add_feature("functional", "Path Type Selector", ["Toggle Linear vs Circular", "Switch visualization"], "high")
add_feature("functional", "Linear Path Rendering", ["Draw straight line", "Mark start and end"], "high")
add_feature("functional", "Circular Path Rendering", ["Draw circle path", "Mark circumference"], "high")
add_feature("functional", "Parameter Inputs", ["Total Length (L) input", "Interval (d) input"], "high")
add_feature("functional", "Planting Mode Selector", ["Both ends", "One end", "Neither end"], "high")
add_feature("functional", "Tree Calculation Logic", ["Calculate Count based on Mode", "Handle division by zero"], "high")
add_feature("functional", "Tree Visualization", ["Render tree icons at intervals", "Match calculated count"], "high")
add_feature("style", "Planting Animation", ["Animate trees popping up one by one", "Show count increasing"], "medium")
add_feature("functional", "Interval/Count Display", ["Show derived 'Intervals'", "Show derived 'Trees'"], "high")
add_feature("functional", "Concept: Interval vs Point", ["Highlight 'Interval' segment", "Highlight 'Tree' point"], "medium")
add_feature("functional", "Formula Display", ["Show dynamic formula (e.g. N = L/d + 1)", "Update based on mode"], "high")
add_feature("functional", "Trap Warning System", ["Alert if L is not multiple of d", "Suggest rounding or exact d"], "medium")
add_feature("functional", "Interactive Dragging (Bonus)", ["Drag end point to change L", "Snap to grid"], "low")
add_feature("style", "Tree Icon Design", ["Custom SVG Tree", "Simple and clear"], "medium")
add_feature("style", "Path Ruler/Measurement", ["Show tick marks on path", "Numbering"], "medium")
add_feature("functional", "Circular Mode Special Case", ["Disable 'End Modes' for circle", "Force Count = Intervals"], "high")
add_feature("functional", "Problem Scenario 1: Street", ["Preset: Linear, Both Ends", "Description text"], "medium")
add_feature("functional", "Problem Scenario 2: Lake", ["Preset: Circular", "Description text"], "medium")
add_feature("functional", "Problem Scenario 3: Stairs", ["Preset: One end (analogy)", "Description text"], "medium")
add_feature("style", "Result Highlight", ["Pulse effect on final answer", "Large font"], "low")
add_feature("functional", "Input Validation", ["Prevent negative L or d", "Max limit to prevent crash"], "high")
add_feature("style", "Responsive Canvas", ["Fit path in view", "Scale trees appropriate"], "medium")
add_feature("functional", "Reset Simulation", ["Clear trees", "Reset inputs"], "low")
add_feature("style", "Legend/Key", ["Tree icon = 1 tree", "Gap icon = 1 interval"], "low")
add_feature("functional", "Sound Effects (Optional)", ["Pop sound on planting", "Mute toggle"], "low")
add_feature("functional", "Step-by-Step Planting", ["'Next Tree' button", "Manual control"], "medium")
add_feature("functional", "Auto-Play Planting", ["'Plant All' button", "Speed control"], "low")
add_feature("functional", "Reflection/Summary", ["End summary modal", "What did we learn?"], "low")
add_feature("functional", "Edge Case Testing", ["L = d", "L < d", "L = 0"], "low")

# CompositeArea Module 111-135
add_feature("functional", "CompositeArea Route Setup", ["Create page component", "Add route /composite-area"], "high")
add_feature("functional", "Shape Canvas Setup", ["Interactive area", "Grid background"], "high")
add_feature("functional", "Define Basic Shapes", ["Rect, Circle, Triangle data structures", "Render functions"], "high")
add_feature("functional", "Draggable Components", ["Make shapes draggable", "Update coordinates"], "high")
add_feature("functional", "Target Shape Outline", ["Draw dotted outline of target", "The goal shape"], "medium")
add_feature("functional", "Shape Splitting (Visual)", ["Pre-defined split pieces", "Click to separate"], "high")
add_feature("functional", "Shape Rotation", ["Rotate buttons/handle", "90 deg increments"], "medium")
add_feature("functional", "Snap to Grid/Target", ["Snap logic", "Feedback on snap"], "medium")
add_feature("functional", "Color Coding Areas", ["Green for positive area", "Red for negative/hole"], "high")
add_feature("functional", "Problem 1: Square minus Circle", ["Load Scenario 1", "Setup shapes"], "high")
add_feature("functional", "Problem 2: Irregular to Rect", ["Load Scenario 2", "Setup shapes"], "high")
add_feature("functional", "Auxiliary Lines Toggle", ["Show hidden lines", "Dashed style"], "medium")
add_feature("functional", "Area Calculation Panel", ["Show A1, A2 values", "Show Total = A1 +/- A2"], "high")
add_feature("style", "Shape Transparency", ["Semi-transparent fill", "See overlaps"], "medium")
add_feature("functional", "Reset Shapes Position", ["Return to start", "Shuffle"], "low")
add_feature("functional", "Completion Detection", ["Check if target filled", "Success animation"], "medium")
add_feature("style", "Confetti Celebration", ["On success", "Particle effects"], "low")
add_feature("functional", "Hint System", ["Show next move", "Highlight piece"], "medium")
add_feature("functional", "Interactive Formula", ["Click shape -> Highlight variable", "Click variable -> Highlight shape"], "medium")
add_feature("style", "Shape Hover Effects", ["Glow border", "Tooltips with dimensions"], "low")
add_feature("functional", "Custom Shape Builder (Advanced)", ["Simple polygon drawing", "(Optional)"], "low")
add_feature("functional", "Undo/Redo Actions", ["History stack", "Buttons"], "low")
add_feature("style", "Mobile Drag Support", ["Touch events", "Prevent scroll while dragging"], "medium")
add_feature("functional", "Lock Shape", ["Prevent accidental moves", "Toggle lock"], "low")
add_feature("functional", "Dimension Labels", ["Show side lengths on shapes", "Dynamic update if scaled"], "medium")

# EquationSolver Module 136-160
add_feature("functional", "EquationSolver Route Setup", ["Create page component", "Add route /equation-solver"], "high")
add_feature("functional", "Balance Scale Component", ["Render visual scale", "Left/Right pans"], "high")
add_feature("functional", "Scale Logic", ["Calculate torque/weight", "Determine tilt angle"], "high")
add_feature("functional", "Equation State", ["Store LHS and RHS terms", "Parsing logic"], "high")
add_feature("functional", "Visual Representation", ["X as box", "Constants as weights"], "high")
add_feature("functional", "Initial Problem Generation", ["Generate ax + b = c", "Random or preset"], "high")
add_feature("functional", "Operation Controls", ["Add, Sub, Mul, Div buttons", "Input value for op"], "high")
add_feature("style", "Action Animation", ["Animate weights appearing/disappearing", "Smoot tilt adjustment"], "medium")
add_feature("functional", "Apply to Both Sides", ["Enforce symmetric operations", "Error if only one side"], "high")
add_feature("functional", "Step History", ["Log each operation", "Show equation transformation"], "medium")
add_feature("functional", "Goal Detection", ["Check if x = result", "Success state"], "high")
add_feature("functional", "Problem 1: ax + b = c", ["Preset config", "Guide text"], "medium")
add_feature("functional", "Problem 2: Simple x + a = b", ["Preset config", "Guide text"], "medium")
add_feature("functional", "Auto-Simplify", ["Combine like terms visual", "Merge weights"], "medium")
add_feature("style", "Balance Physics", ["Damped oscillation", "Realistic feel"], "low")
add_feature("functional", "Hint: What to do next", ["Suggest 'Subtract b'", "Highlight button"], "medium")
add_feature("functional", "Reset Equation", ["Restart current problem", "Clear history"], "low")
add_feature("style", "Variable Styling", ["Distinct color for X", "Distinct shape"], "low")
add_feature("functional", "Negative Numbers Support", ["Visual representation (balloon?)", "Or restrict to positive"], "medium")
add_feature("functional", "Division Visualization", ["Split X box into parts", "Split weights"], "medium")
add_feature("functional", "Multiplication Visualization", ["Duplicate X boxes", "Duplicate weights"], "medium")
add_feature("functional", "Input Validation", ["Prevent invalid ops", "Divide by zero"], "high")
add_feature("style", "Equation Text Display", ["Large centered equation", "Update real-time"], "high")
add_feature("functional", "Verify Solution", ["Substitute back check", "Show checkmark"], "medium")
add_feature("style", "Learning Objectives Panel", ["Show 'Golden Rule'", "Keep balanced"], "low")

# WordProblems Module 161-180
add_feature("functional", "WordProblems Route Setup", ["Create page component", "Add route /word-problems"], "high")
add_feature("functional", "Bar Model Component", ["SVG/Canvas bars", "Label support"], "high")
add_feature("functional", "Problem Text Parser", ["Display problem text", "Highlight keywords"], "high")
add_feature("functional", "Problem 1: Sum/Multiple", ["Load data", "Setup model"], "high")
add_feature("functional", "Problem 2: Catch-up", ["Load data", "Setup model"], "high")
add_feature("functional", "Interactivity: Adjust Bar", ["Slider to change X", "Other bars update"], "medium")
add_feature("functional", "Variable Mapping", ["Show which bar is 'x'", "Show relations '4x'"], "high")
add_feature("functional", "Braces and Labels", ["Draw braces for totals", "Draw braces for differences"], "high")
add_feature("style", "Animation: Growth", ["Animate bars changing length", "Smooth updates"], "medium")
add_feature("functional", "Equation Builder", ["Drag numbers to form eq", "Or select correct eq"], "medium")
add_feature("functional", "Validation Mode", ["Check if user model matches text", "Feedback"], "medium")
add_feature("style", "Problem Story Mode", ["Step 1: Read", "Step 2: Model", "Step 3: Solve"], "medium")
add_feature("functional", "Numeric Solution", ["Calculate final answer", "Input field to check"], "medium")
add_feature("style", "Visual Hints", ["Arrow pointing to key relation", "Color match"], "low")
add_feature("functional", "Reset Problem", ["Clear model", "Restart"], "low")
add_feature("functional", "Custom Problem Input", ["Allow typing simple numbers", "Template update"], "low")
add_feature("style", "Bar Colors", ["Distinct per entity", "Consistent legend"], "low")
add_feature("functional", "Comparison View", ["Show Model vs Equation", "Bridge the gap"], "medium")
add_feature("functional", "Difficulty Levels", ["Easy/Hard nums", "Hide/Show hints"], "low")
add_feature("style", "Character Avatars", ["Icons for 'Jia', 'Yi'", "Friendly visuals"], "low")

# DecimalOperations Module 181-205
add_feature("functional", "DecimalOps Route Setup", ["Create page component", "Add route /decimal-ops"], "high")
add_feature("functional", "Grid 10x10 Component", ["Render 100 cells", "Coordinate system"], "high")
add_feature("functional", "Input Decimals", ["Inputs for 0.X and 0.Y", "Step 0.1"], "high")
add_feature("functional", "Row Highlighting", ["Highlight N rows for first num", "Color 1"], "high")
add_feature("functional", "Col Highlighting", ["Highlight M cols for second num", "Color 2"], "high")
add_feature("functional", "Overlap Calculation", ["Detect intersection", "Color Mixed"], "high")
add_feature("functional", "Count Display", ["Show Total cells", "Show Overlap cells"], "high")
add_feature("functional", "Multiplication Formula", ["Display 0.X * 0.Y = ?", "Update result"], "high")
add_feature("style", "Cell Animation", ["Fill cells sequentially", "Visual counting"], "medium")
add_feature("functional", "Zoom/Subdivision (Advanced)", ["Break 0.1 into 0.01", "Zoom in grid"], "medium")
add_feature("functional", "Shift Decimal Point Anim", ["Visual logic for point shift", "x10, x100"], "medium")
add_feature("functional", "Reset Grid", ["Clear selection", "Reset inputs"], "low")
add_feature("style", "Grid Labels", ["Axis labels 0.1, 0.2...", "Corner 0"], "low")
add_feature("functional", "Interactive Clicking", ["Click to select rows/cols", "Alternative input"], "low")
add_feature("functional", "Problem Generator", ["Random Simple Decimals", "Random Hard"], "medium")
add_feature("functional", "Area Analogy Text", ["Explain Length * Width", "Connect to geometry"], "medium")
add_feature("style", "Responsive Grid", ["Resize with window", "Keep square aspect"], "medium")
add_feature("functional", "Error Handling", ["Inputs > 1.0 handling", "Expand grid?"], "medium")
add_feature("functional", "Step Mode", ["1. Shade rows", "2. Shade cols", "3. Count"], "medium")
add_feature("style", "Result Popover", ["Show result near overlap", "Large text"], "low")
add_feature("functional", "Division Visualization", ["Reverse: Start with Area", "Find side"], "low")
add_feature("style", "Color Blind Mode", ["Patterns instead of just colors", "Texture"], "low")
add_feature("functional", "Export Image", ["Save grid as PNG", "For homework"], "low")
add_feature("functional", "Tutorial Overlay", ["First time user guide", "Dismissible"], "low")
add_feature("functional", "Keyboard Support", ["Arrow keys adjust nums", "Enter to solve"], "low")

# Final Polish & Deployment 206-215
add_feature("functional", "Full Regression Test", ["Manual check all modules", "Fix glitches"], "high")
add_feature("functional", "Performance Audit", ["Lighthouse check", " Optimize images"], "medium")
add_feature("functional", "Build Production", ["Run npm run build", "Check dist folder"], "high")
add_feature("functional", "Deployment Script", ["Setup gh-pages", "Deploy workflow"], "high")
add_feature("functional", "Readme Update", ["Document features", "Add screenshots"], "medium")
add_feature("functional", "License File", ["Add MIT License", "Review"], "low")
add_feature("functional", "Contributing Guide", ["Add CONTRIBUTING.md", " Guidelines"], "low")
add_feature("style", "Final UI Polish", ["Consistent margins", "Consistent fonts"], "medium")
add_feature("functional", "Cross-Browser Check", ["Chrome/Firefox/Safari", "Fix flexbox issues"], "medium")
add_feature("functional", "Mobile Usability Check", ["Touch targets sizing", "Viewport check"], "medium")

# Write to file
with open("/root/workspace/mathweb/feature_list.json", "w", encoding="utf-8") as f:
    json.dump(features, f, indent=2, ensure_ascii=False)

print(f"Generated {len(features)} features in feature_list.json")
